import 'dart:convert';
import "api.dart";
import "./bean/service.dart";

typedef RequestCallBack<T> = void Function(T value);

class HomeApi {
  static const String ApiServiceList =
      "/method/frappe.apis.apps.services.items";

  void getServiceList(RequestCallBack requestCallBack) async {
    final result = await Api.get(ApiServiceList);
    // Map<String, dynamic> jsonMap = json.decode(result.data);

    Autogenerated serviceList = Autogenerated.fromJson(result.data);

    print(serviceList);
    requestCallBack(serviceList);
  }
}
