class Autogenerated {
  Status status;
  Data data;

  Autogenerated({this.status, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status =
        json['status'] != null ? new Status.fromJson(json['status']) : null;
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.status != null) {
      data['status'] = this.status.toJson();
    }
    if (this.data != null) {
      data['data'] = this.data.toJson();
    }
    return data;
  }
}

class Status {
  String message;
  int code;

  Status({this.message, this.code});

  Status.fromJson(Map<String, dynamic> json) {
    message = json['message'];
    code = json['code'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['message'] = this.message;
    data['code'] = this.code;
    return data;
  }
}

class Data {
  List<Display> display;

  Data({this.display});

  Data.fromJson(Map<String, dynamic> json) {
    if (json['display'] != null) {
      display = new List<Display>();
      json['display'].forEach((v) {
        display.add(new Display.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.display != null) {
      data['display'] = this.display.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Display {
  String name;
  String namingSeries;
  String title;

  Display({this.name, this.namingSeries, this.title});

  Display.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    namingSeries = json['naming_series'];
    title = json['plan_name'] ?? json['service_project_name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['naming_series'] = this.namingSeries;
    data['title'] = this.title;
    return data;
  }
}
